"""
Orchestrates a before/after load test comparison and writes reports/load_test_report.md.

"Before" runs the FastAPI service unoptimized: caching disabled and a minimal DB
connection pool (pool_size=2, max_overflow=0), so every request pays for a fresh
schema-relevance lookup, a fresh "LLM" generation call, and contends hard for the one
or two available DB connections.

"After" runs the same service with caching enabled (schema-relevance results and
repeated-question SQL generations are cached) and a larger connection pool
(pool_size=20, max_overflow=10) -- the configuration documented in .env.example.

Requires: docker compose up (postgres+redis), db/seed.py already run, and the
`locust` package installed (pip install -r requirements.txt).

Usage:
    python tests/load/run_load_comparison.py [--users 50] [--spawn-rate 10] [--duration 45s]
"""
from __future__ import annotations

import argparse
import csv
import os
import signal
import subprocess
import sys
import time
from pathlib import Path

import httpx

ROOT = Path(__file__).resolve().parents[2]
REPORTS_DIR = ROOT / "reports"
HOST = "http://127.0.0.1:8010"

BASE_ENV = {
    "DATABASE_URL": "postgresql+asyncpg://postgres:postgres@localhost:5432/analytics",
    "REDIS_URL": "redis://localhost:6379/0",
    "LLM_PROVIDER": "mock",
    "APP_ENV": "prod",  # JSON logs instead of the (slower) dev console renderer
    "LOG_LEVEL": "WARNING",
}

CONFIGS = {
    "before_unoptimized": {
        **BASE_ENV,
        "CACHE_ENABLED": "false",
        "DB_POOL_MIN_SIZE": "1",
        "DB_POOL_MAX_SIZE": "1",
        "DB_POOL_MAX_OVERFLOW": "0",
    },
    "after_optimized": {
        **BASE_ENV,
        "CACHE_ENABLED": "true",
        "DB_POOL_MIN_SIZE": "20",
        "DB_POOL_MAX_SIZE": "20",
        "DB_POOL_MAX_OVERFLOW": "10",
    },
}


def wait_for_health(timeout: float = 20.0) -> bool:
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            r = httpx.get(f"{HOST}/health", timeout=2.0)
            if r.status_code == 200:
                return True
        except httpx.HTTPError:
            pass
        time.sleep(0.5)
    return False


def run_phase(name: str, env_overrides: dict, users: int, spawn_rate: int, duration: str) -> Path:
    print(f"\n=== Phase: {name} ===")
    env = {**os.environ, **env_overrides}
    server = subprocess.Popen(
        [sys.executable, "-m", "uvicorn", "app.main:app", "--host", "127.0.0.1", "--port", "8010"],
        cwd=str(ROOT),
        env=env,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    try:
        if not wait_for_health():
            raise RuntimeError(f"server did not become healthy for phase {name}")
        print(f"Server up, running locust for {duration} with {users} users (spawn rate {spawn_rate})...")

        csv_prefix = REPORTS_DIR / f"load_{name}"
        locust_cmd = [
            sys.executable, "-m", "locust",
            "-f", str(ROOT / "tests" / "load" / "locustfile.py"),
            "--host", HOST,
            "--headless",
            "-u", str(users),
            "-r", str(spawn_rate),
            "-t", duration,
            "--csv", str(csv_prefix),
            "--csv-full-history",
        ]
        result = subprocess.run(locust_cmd, cwd=str(ROOT), env=env, capture_output=True, text=True)
        print(result.stdout[-2000:])
        if result.returncode not in (0, 1):  # locust returns 1 if failure threshold-like conditions trip
            print(result.stderr[-2000:])
        return Path(f"{csv_prefix}_stats.csv")
    finally:
        server.send_signal(signal.SIGTERM if os.name != "nt" else signal.SIGTERM)
        try:
            server.wait(timeout=10)
        except subprocess.TimeoutExpired:
            server.kill()


def parse_stats_csv(path: Path) -> dict:
    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            if row["Name"] == "Aggregated":
                return row
    return {}


def build_report(results: dict) -> str:
    lines = [
        "# Load Test Report",
        "",
        "Generated by tests/load/run_load_comparison.py against the /query endpoint",
        "(mock LLM provider, real Postgres + Redis via docker-compose).",
        "",
        "| Metric | Before (no cache, pool=1) | After (cache + pool=20) |",
        "|---|---|---|",
    ]

    def g(phase, key, cast=float, default="0"):
        return cast(results[phase].get(key, default) or default)

    for phase in ("before_unoptimized", "after_optimized"):
        if phase not in results:
            return "Load test did not complete for all phases; see console output."

    req_count_b = g("before_unoptimized", "Request Count")
    req_count_a = g("after_optimized", "Request Count")
    fail_b = g("before_unoptimized", "Failure Count")
    fail_a = g("after_optimized", "Failure Count")
    rps_b = g("before_unoptimized", "Requests/s")
    rps_a = g("after_optimized", "Requests/s")
    p50_b = g("before_unoptimized", "50%")
    p50_a = g("after_optimized", "50%")
    p95_b = g("before_unoptimized", "95%")
    p95_a = g("after_optimized", "95%")

    err_rate_b = (fail_b / req_count_b * 100) if req_count_b else 0
    err_rate_a = (fail_a / req_count_a * 100) if req_count_a else 0

    lines += [
        f"| Total requests | {req_count_b:.0f} | {req_count_a:.0f} |",
        f"| Requests/sec | {rps_b:.2f} | {rps_a:.2f} |",
        f"| Requests/min (RPM) | {rps_b * 60:.0f} | {rps_a * 60:.0f} |",
        f"| Error rate | {err_rate_b:.2f}% | {err_rate_a:.2f}% |",
        f"| p50 latency (ms) | {p50_b:.0f} | {p50_a:.0f} |",
        f"| p95 latency (ms) | {p95_b:.0f} | {p95_a:.0f} |",
    ]
    if p95_b > 0:
        improvement = (p95_b - p95_a) / p95_b * 100
        lines.append(f"| p95 improvement | -- | {improvement:.1f}% faster |")
    if rps_b > 0:
        throughput_gain = (rps_a - rps_b) / rps_b * 100
        lines.append(f"| Throughput improvement | -- | {throughput_gain:.1f}% higher |")

    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--users", type=int, default=50)
    parser.add_argument("--spawn-rate", type=int, default=10)
    parser.add_argument("--duration", default="45s")
    args = parser.parse_args()

    REPORTS_DIR.mkdir(exist_ok=True)
    results = {}
    for name, env_overrides in CONFIGS.items():
        stats_path = run_phase(name, env_overrides, args.users, args.spawn_rate, args.duration)
        if stats_path.exists():
            results[name] = parse_stats_csv(stats_path)
        time.sleep(2)

    report = build_report(results)
    out_path = REPORTS_DIR / "load_test_report.md"
    out_path.write_text(report, encoding="utf-8")
    print("\n" + report)
    print(f"Report written to {out_path}")


if __name__ == "__main__":
    main()
